# Generated by Django 4.1.7 on 2023-04-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_app', '0002_employee_services_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=1931804338, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(default=5425299397, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_id',
            field=models.IntegerField(default=2296132489, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentrepair',
            name='equipment_repair_id',
            field=models.IntegerField(default=4073245072, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='equipmentusage',
            name='equipment_usage_id',
            field=models.IntegerField(default=9798733006, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.IntegerField(default=9196319169, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_id',
            field=models.IntegerField(default=8368447793, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_id',
            field=models.IntegerField(default=4221647608, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(default=9046539720, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trainedemployee',
            name='trained_employee_id',
            field=models.IntegerField(default=6994275297, primary_key=True, serialize=False, unique=True),
        ),
    ]
